# Generated by Django 4.2.16 on 2024-09-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExhibitionApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("country", models.CharField(max_length=50)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=10)),
                ("application_type", models.JSONField()),
                ("designer_category", models.JSONField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="designerregistration", name="application_types",
        ),
        migrations.RemoveField(model_name="designerregistration", name="designer",),
        migrations.RemoveField(
            model_name="designerregistration", name="designer_categories",
        ),
        migrations.DeleteModel(name="ApplicationType",),
        migrations.DeleteModel(name="Designer",),
        migrations.DeleteModel(name="DesignerCategory",),
        migrations.DeleteModel(name="DesignerRegistration",),
    ]
