# Generated by Django 4.2.16 on 2024-09-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignerRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "application_type",
                    models.JSONField(
                        choices=[
                            ("exhibition", "Exhibition"),
                            ("runway", "Runway"),
                            ("both", "Both"),
                        ]
                    ),
                ),
                (
                    "designer_category",
                    models.JSONField(
                        choices=[
                            ("Fashion Designer", "Fashion Designer"),
                            ("Exclusive Designer", "Exclusive Designer"),
                            ("Stylists", "Stylists"),
                            ("Accessory Designer", "Accessory Designer"),
                            ("Emerging Designer", "Emerging Designer"),
                            ("Established Designer", "Established Designer"),
                        ]
                    ),
                ),
            ],
        ),
    ]
