# Generated by Django 4.2.16 on 2024-10-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_exhibitionapplication_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitionapplication",
            name="facebook_id",
            field=models.CharField(default="text", max_length=100),
        ),
        migrations.AddField(
            model_name="exhibitionapplication",
            name="instagram_id",
            field=models.CharField(default="text", max_length=100),
        ),
        migrations.AddField(
            model_name="exhibitionapplication",
            name="tiktok_id",
            field=models.CharField(default="text", max_length=100),
        ),
    ]
