# Generated by Django 4.2.16 on 2024-09-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_designerregistration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designerregistration",
            name="application_type",
            field=models.CharField(
                choices=[
                    ("exhibition", "Exhibition"),
                    ("runway", "Runway"),
                    ("both", "Both"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="designerregistration",
            name="designer_category",
            field=models.CharField(
                choices=[
                    ("Fashion Designer", "Fashion Designer"),
                    ("Exclusive Designer", "Exclusive Designer"),
                    ("Stylists", "Stylists"),
                    ("Accessory Designer", "Accessory Designer"),
                    ("Emerging Designer", "Emerging Designer"),
                    ("Established Designer", "Established Designer"),
                ],
                max_length=30,
            ),
        ),
    ]
