# Generated by Django 4.2.16 on 2024-09-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_designerregistration_application_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("exhibition", "Exhibition"),
                            ("runway", "Runway"),
                            ("both", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DesignerCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Fashion Designer", "Fashion Designer"),
                            ("Exclusive Designer", "Exclusive Designer"),
                            ("Stylists", "Stylists"),
                            ("Accessory Designer", "Accessory Designer"),
                            ("Emerging Designer", "Emerging Designer"),
                            ("Established Designer", "Established Designer"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="designerregistration", name="application_type",
        ),
        migrations.RemoveField(
            model_name="designerregistration", name="designer_category",
        ),
        migrations.AddField(
            model_name="designerregistration",
            name="application_type",
            field=models.ManyToManyField(to="users.applicationtype"),
        ),
        migrations.AddField(
            model_name="designerregistration",
            name="designer_category",
            field=models.ManyToManyField(to="users.designercategory"),
        ),
    ]
