# Generated by Django 4.2.16 on 2024-09-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_blog_gallery_upcomingevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="image", field=models.ImageField(upload_to="blog/"),
        ),
    ]
