# Generated by Django 4.2.16 on 2024-09-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_blog_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="MustRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="Gallery-images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("body", models.TextField(default="Paste", null=True)),
            ],
        ),
        migrations.DeleteModel(name="Gallery",),
    ]
